export const CATEGORIES = [
  {
    categoryName: "Tarjetas",
    keys: [
      "Tarjeta",
      "tarjetas",
      "QUADRO",
      "GEFORCE",
      "SAPPHIRE",
      "GEFORC",
      "ASROCK",
      "RTX",
      "GTX",
    ],
  },
  {
    categoryName: "Sillas",
    keys: ["Sillas", "silla", "akracing"],
  },
  {
    categoryName: "Perfiféricos",
    keys: [
      "INALAMBRICA",
      "REDRAGON",
      "Diadema",
      "Auriculares",
      "Audifonos",
      "Mouse",
      "Teclado",
      "Keyboard",
      "ADAPTADOR",
      "GAMEPAD",
      "COOLER MASTER",
      "K55+MSE",
      "K552-BB",
      "2en1",
      "4en1",
      "POWER BANK",
      "REGULADOR",
      "UPS",
      "PALANCA",
      "CABLE",
      "CAMARA",
      "SCREEN PANEL",
      "DECK",
      "ROUTER",
      "TERMOMETRO",
      "TP-LINK",
      "BENQ",
      "S41",
      "Timón",
      "Timon",
      "Volante",
      "Inalámbricos",
      "Inalambricos",
      "Capturadora",
      "Microfono",
      "Micrófono",
      "Cámara",
      "Key Light",
      "CAM ",
      "Control",
      "Joystick",
      "CONVERTIDOR",
      "CARGADOR",
      "QUEMADORES",
      "SOLUCION POS",
      "MULTIFUNCIONA",
      "INYECCION",
      "MATRIZ DE PUNTO",
      "LASER",
      "ANTENA",
      "BLUETOOTH MINI",
      "CADDY",
      "CRHOME CAST",
      "CAST",
      "SPLITTER",
      "NEOPRENO",
      "POPSOCKETS",
      "TELON MANUAL",
      "GENERACION",
      "PROYECTOR",
      "SWICHT",
      "EXTENSOR",
      "SWITCH",
      "WORKFORCE",
      "MONEDERO",
      "CANON",
      "EPSON",
      "SISTEMA DE RECARGA",
      "SL-M4030ND",
      "FULL GD",
      "ESCANER",
      "SCANNER",
      "SCAN",
      "Wireless",
      "PY9-00004",
      "REF N9Z",
      "Funda",
      "CPE TendA",
      "Google Home",
      "Inyector",
      "Pin Loto",
      "Medias Loto",
      "Loto",
      "Faceplate",
      "Tornillo",
      "Pilas",
      "Sistema WiFi",
      "Wacom",
      "Thermaltake 4 En 1",
      "Headset",
      "Captura",
      "Razer",
      "CUADRO",
      "Panel",
    ],
  },
  {
    categoryName: "Pantallas",
    keys: [
      "VGA",
      "GSYNC",
      "Monitor",
      "Pantalla",
      "LED",
      "IPS",
      "CURVO",
      "ULTRAWIDE",
      "4K",
      "144HZ",
      "60hz",
      "1080P",
      "1ms",
    ],
  },
  {
    categoryName: "Cajas",
    keys: [
      "TOWER",
      "ATX",
      "Caja",
      "Chase",
      "Chasis",
      "MX410",
      "BLUNDE SPEC",
      "CARBIDE",
      "SPEC",
      "GAMER CRYSTAL",
      "V100 VENTANA",
      "CASE",
      "MX350RGB",
      "DARK BLADER",
      "BLAZER ESSENCE",
      "celesta",
    ],
  },
  {
    categoryName: "Refrigeración",
    keys: [
      "240DDC",
      "AIRFLOW",
      "FAN",
      "LIQUID",
      "COOLER",
      "Refrigeración",
      "Refrigeracion",
      "COMBO COOLER MASTER",
      "VENTILADOR",
      "DISIPADOR",
      "REFRIGERANTE",
      "PASTA",
      "DISCIPADOR",
    ],
  },
  {
    categoryName: "Procesadores",
    keys: [
      "Procesador",
      "INTEL",
      "RYZEN",
      "I9",
      "I7",
      "I5",
      "I3",
      "CELERON",
      "PENTIUM",
    ],
  },
  {
    categoryName: "Memorias",
    keys: [
      "CRYSTAL",
      "3200",
      "RAM",
      "DDR4",
      "DDR3",
      "DDR2",
      "Memoria",
      "USB",
      "DDR",
      "TRIDENT",
      "3000 MHZ",
      "VENGEANCE",
      "VENGANCE",
      "3600 mhz",
    ],
  },
  {
    categoryName: "MotherBoard",
    keys: [
      "Board",
      "madre",
      "B460",
      "Z490",
      "B450",
      "V.R.4DR4",
      "ASROCK.RADEON",
      "B460",
      "B550",
      "B450",
      "A520M",
      "H410M",
    ],
  },
  {
    categoryName: "Licencias",
    keys: [
      "Licencia",
      "ESET",
      "KARSPESKY",
      "TOTAL SECURITY 2019 SPANISH 10 USUARIOS",
      "(iva inc)",
      "OFFICE",
      "window",
      "OFICCE",
      "OFFICCE",
      "MOBILE SECURITY",
    ],
  },
  {
    categoryName: "Computadores",
    keys: ["Portatil", "PC", "Laptop", "Portátil", "GF75", "HP PRO"],
  },
  {
    categoryName: "Fuentes",
    keys: ["FUENTE", "CV650", "CV450", "CV550W", "GENERICA 750W", "REAL 550W"],
  },
  {
    categoryName: "DISCO DURO",
    keys: [
      "SSD",
      "SD",
      "DISCO",
      "DURO",
      "SOLIDO",
      "WESTERN DIGITAL",
      "SATA III",
      "D.D",
      "adata",
      "Solida",
    ],
  },
  {
    categoryName: "Parlantes",
    keys: [
      "S120",
      "Z313",
      "Z323",
      "Z337",
      "Z607",
      "Z906",
      "TRUST REMO",
      "SUBWOOFER",
      "PARLANTE",
      "SURROUND",
    ],
  },
  {
    categoryName: "Celulares",
    keys: ["iphone", "celular"],
  },
  {
    categoryName: "Combo",
    keys: ["Combo"],
  },
];
